### ISSUE TITLE
Readme says 2020.3 is required but HEAD of main requires 2021.2

### ISSUE THREAD

**Issue by andybak** [cowtrix/voxul#8]
Texture2D.Reinitialize breaks on earlier versions.

**Comment by cowtrix** [comment]
Thanks Andy, I let the backwards compatibility go a bit. Fixed now.

**Comment by cowtrix** [comment]
I've noticed however that the ShaderGraph assets aren't backwards compatible to 2020. Fun. Not sure what the best way to fix that is...
